#encoding:utf-8

module Gasolina_app
    class Localizacion
        attr_reader provincia: String
        attr_reader municipio: String
        attr_reader localidad: String
        attr_reader cod_postal: Integer 
        attr_reader direccion: String
        attr_reader longitud: String
        attr_reader latitud: String

        def initialize: (provincia: String, municipio: String, localidad: String, cod_postal: Integer, 
                        direccion: String, longitud: String, latitud: String) -> void
    end 
end